language: node_js

node_js: stable

services:
  - redis-server

install:
  - yarn

before_install:
  sudo service redis-server start --bind 127.0.0.1

script:
  - npm run test

after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov

cache:
  yarn: true
  directories:
    - node_modules
