language: node_js

node_js: stable

install:
  - yarn

script:
  - npm run docs:build
  - cd docs/.vuepress/dist
  - echo 'rsshub.js.org' > CNAME
  - git init
  - git config user.name "Travis CI"
  - git config user.email "no-reply@html.love"
  - git add -A
  - git commit -m 'deploy'
  - git push -f 'https://${GH_TOKEN}@${GH_REF}' master:gh-pages

env:
 global:
   - GH_REF: github.com/DIYgod/RSSHub.git

cache:
  yarn: true
  directories:
    - node_modules