name: format

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message: "👍感谢提交该 PR，请确保使用了 [PR 模板](https://github.com/DIYgod/RSSHub/blob/master/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md) 以便于测试。

👍Thanks for the PR, please make sure you have followed the [PR template](https://github.com/DIYgod/RSSHub/blob/master/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md) to simplify the testing."
